### PR TITLE
fix diagnostic sign issues

### PR DESCRIPTION
**Pull request by cairijun**
This PR should fix two diagnostic signs related issues:
* #758 If multiple diagnostic messages were reported on a single line, multiple signs would be added but only one of them would be removed after the errors were resolved. I think we can just use the most severe one and drop the others  on one line.
* #765 Limitation on number of signs was dropped.

@mhuttner @PierreLeidbring @mburakov Mind helping verify if is this fix you issues?

### CODE REVIEW

**Comment by AdaShoelace** [comment]
This seems to fix the issue with the "error crosses" not getting removed from the gutter. However the little "i" is still persisting even though there is no error, warning or other reason to.

**Comment by mburakov** [comment]
Hi @richardtsai, thank you for taking a look. ~~I don't have any experience with rust, neither a prepared build environment. But I will be happy to try a prebuilt binary if you can share one.~~

It appeared to be easier than I expected. Your change fixes my issue. Thanks again!

**Comment by cairijun** [comment]
> This seems to fix the issue with the "error crosses" not getting removed from the gutter. However the little "i" is still persisting even though there is no error, warning or other reason to.

@PierreLeidbring 
could you provide a reproducible example? code, language server & operations should be sufficient

**Comment by cairijun** [comment]
I think I just found the problem. After lines were deleted, existing signs beyond the current viewport might jump in but be ignored by the viewport filter when calculating `signs_prev`. As the number of signs in `state.signs` is already limited by the viewport filter when adding new signs, I suppose we can just mark all the existing signs as obsolete without notable performance penality.

@PierreLeidbring Does the latest commit fix you issue?

**Comment by AdaShoelace** [comment]
@richardtsai No it does not. Now it marks all my imports with the yellow triangle and the row on which the error used to occur still has a red cross even though the error is resolved.

**Comment by cairijun** [comment]
I cannot reproduce the issues you mentioned, with either `clangd`, `pyls` or `rls`. Could you tell me which langserver you are using and a piece of example code? @PierreLeidbring

**Comment by AdaShoelace** [comment]
To reproduce the error just create a new bin-project with `cargo new foo`.
Inside the project go down to the `println!("hello world!");`, press `shift + o`, write `String::` and wait for the error to occur. Remove the `String::` (which resolves the error). Now the `println!("Hello world!")`-line still have the red cross in the gutter.

From my vimrc:
```
let g:LanguageClient_serverCommands = {
			\ 'rust': ['rustup','run','nightly', 'rls'],
			\}

let g:LanguageClient_autoStart = 1
```

I tried using just `'rust': ['rls']` instead of `'rust': ['rustup','run','nightly', 'rls']`. That resolves the issue with the persisting signs but autocompletion stops working.

**Comment by cairijun** [comment]
unable to reproduce:
https://dump.video/i/ZRXVLD.mp4

are you sure you are using the `languageclient` executable built from the commits in this PR?

**Comment by AdaShoelace** [comment]
I think so at least. Installed it using:
```
Plug 'richardtsai/LanguageClient-neovim', {
			\ 'branch': 'fix_diag_signs',
			\ 'do': 'bash install.sh'
			\}

```
And updated with `:PlugUpdate` immediately after your first message today.

**Comment by cairijun** [comment]
`install.sh` just downloads the official prebuilt executable
you have to `cargo build --release` followed by `mv target/release/languageclient bin/`

**Comment by AdaShoelace** [comment]
My bad for not reading `install.sh`.
It seems to be working correctly with the latest fix.
Thanks!

**Comment by cairijun** [comment]
@autozimu any thoughts? This seem to be blocking many users, expecially those of `clangd` or `pyls`.

**Comment by autozimu** [comment]
Thanks!

**Comment by sriharshachilakapati** [comment]
I had a temporary fix for this one till now at some point that I didn't notice this.

~~~vimscript
autocmd BufWritePre *.purs :sign unplace *
~~~

Thanks for this fix!!

**Comment by jamesob** [comment]
Can you consider cutting a new release so that this fix is included in a regular `:PlugUpdate` workflow? If I hadn't dug through this issue thread and saw your note about manually building with `cargo`, I'd just uninstall your plugin permanently because the out-of-date gutter is so annoying.

**Comment by autozimu** [comment]
This is included in latest release.

To be clear, you’re “free” to do whatever you like. I made this plugin
mostly for fun and published in hope it might be useful to some people,
which may or may not be including you. You’re definitely not obligated to
use it in any way.

**Comment by jamesob** [comment]
Hm, well whether it's in the latest release or not, simply running `:PlugUpdate` (i.e. having the latest git clone of the `next` branch) didn't fix the problem; it was only resolved with the manual `cargo` stuff.

Sorry, didn't mean to come off so abrasively. Thank you for your work - it's very valuable and this kind of system improves my development experience quite a bit. I just wanted to emphasize that such a bug could scare off potential users quite easily.

**Comment by autozimu** [comment]
Updating the repo itself won’t get the latest binary build. You had to run
the install script or let plugin manager to do the work.

**Comment by jamesob** [comment]
Yeah, sure, but what I did was run `:PlugUpdate` which (if I understand correctly) should also run the `do:` post-update hook, which is `bash install.sh` - so something with that seems broken.

**Comment by jamesob** [comment]
Yep, just confirmed that running `install.sh` causes a regression in this behavior (on 41c948e05532a92b27c9ef0509cea651592d6bb5).

**Comment by Anrock** [comment]
`install.sh` only downloads latest binary. If there is no release cut then there is no binary for it and `install.sh` would not download anything.

**Comment by jamesob** [comment]
> If there is no release cut then there is no binary for it and install.sh would not download anything.

I verified a new binary was downloaded when I ran `install.sh`. To be clear, the issue this PR fixes is still broken per the installation/update instructions in the README.

**Comment by autozimu** [comment]
`install.sh` actually will always download the latest binary. I'm pretty sure this PR has been included in latest binary release, i.e., version 0.1.146.

@jamesob If it is "broken", can you file an issue with detailed reproduction steps? It's not clear what wasn't working from "broken".

**Pull request merged**
