### PR TITLE
Find ultisnips and fixes snippets.

### PR DESCRIPTION
**Pull request by demelev**
Fixes autocompletion with snippets expanding for nvim-completion-manager

### CODE REVIEW

**Comment by autozimu** [comment]
Thanks for contributing.

Were you able to get snippet working with nvim-completion-manager and this project? What snippet plugin did you use?

**Comment by demelev** [comment]
Yes, I made it work with UltiSnips plugin and nvim-completion-manager.
Lately I've been using SpaceVim config for neovim and it requires some tweaks.
Long story short, I mapped \<Enter> to expand the snippet if it is possible.
Here is some modified snippets form SpaceVim:

```vim
function! mapping_enter_expandable()
    let snippet = UltiSnips#ExpandSnippetOrJump()
    if g:ulti_expand_or_jump_res > 0
      return snippet
    elseif pumvisible()
      return "\<c-y>"
    else
      return "\<ENTER>"
    endif
endfunction

 imap <silent><CR> "\<C-R>=mapping_enter_expandable()\<cr>"
 snoremap <silent> <CR> <ESC>:call UltiSnips#JumpForwards()<CR>

  function! mapping_tab_expandable()
    if pumvisible()
      return "\<C-n>"
    else
        return "\<TAB>"
      endif
    endif
  endfunction

  function! mapping_i_tab() abort
    if getline('.')[col('.')-2] ==# '{'&& pumvisible()
      return "\<C-n>"
    endif
    return "\<C-R>=mapping_tab_expandable()\<cr>"
  endfunction


  imap <silent><expr><S-TAB> mapping_i_tab()
  snoremap <silent> <TAB> <ESC>:call UltiSnips#JumpForwards()<CR>
  snoremap <silent> <S-TAB> <ESC>:call UltiSnips#JumpBackwards()<CR>

  function! mapping_shift_tab() abort
    return pumvisible() ? "\<C-p>" : "\<C-R>=UltiSnips#JumpForwards()\<CR>\<C-R>=cmp#ultisnips#JumpForward()\<CR>"
  endfunction
   imap <silent><expr><S-TAB> mapping_shift_tab()

```
kapture 2018-04-02 at 0 09 19

**Comment by autozimu** [comment]
Merged in 0845577074ad3656838561bd1d075eca6b9f5c9f. Thanks.

Example configuration with nvim-completion manager and ultisnips
```vim
Plug 'roxma/nvim-completion-manager'
imap <expr> <CR> (pumvisible() ? "\<C-Y>\<Plug>(expand_or_cr)" : "\<CR>")
imap <expr> <Plug>(expand_or_cr) (cm#completed_is_snippet() ? "\<C-U>" : "\<CR>")
Plug 'SirVer/ultisnips'
let g:UltiSnipsExpandTrigger = "<Plug>(ultisnips_expand)"
inoremap <silent> <C-U> <C-R>=cm#sources#ultisnips#trigger_or_popup("\<Plug>(ultisnips_expand)")<CR>
let g:UltiSnipsJumpForwardTrigger = "<C-J>"
let g:UltiSnipsJumpBackwardTrigger = "<C-K>"
```

**Comment by ahmedelgabri** [comment]
@autozimu I'm having a problem with these lines:

```vim
imap <expr> <CR> (pumvisible() ? "\<C-Y>\<Plug>(expand_or_cr)" : "\<CR>")
imap <expr> <Plug>(expand_or_cr) (cm#completed_is_snippet() ? "\<C-U>" : "\<CR>")
```

When I press `<CR>` it prints the snippet plus the string `<Plug>(expand_or_cr)` instead of triggering `<C-Y><Plug>(expand_or_cr)`, any clue why?

**Pull request closed without merging**
