### PR TITLE
Make env configurable

### PR DESCRIPTION
**Pull request by DeltaEvo**
This could simplify configuration (see #107)

### CODE REVIEW

**Comment by autozimu** [comment]
Instead of specifying a different env, what about of passing current env? Which release the burdens of user from configuration once more.

**Comment by DeltaEvo** [comment]
We need user env for some variables like PATH (and some language clients could use others ?), so I don't know what to do ... :smile:

**Comment by autozimu** [comment]
I mean in most cases, user would still need to configure those environment variables in their shell rc files to make language servers work. nvim will be started from that same shell environment, so will nvim python host process, so will the langauge server process this plugin launch. Going this way, their language servers will not only work for this plugin, but also VSCode, Emacs etc.

Whenever language server needs access to extra environment variables, user shall went to modify their shell rc files instead of this plugin settings.

Thanks for the work whereas I don't see significant benefits by adding this extra layers within this plugin.

**Comment by DeltaEvo** [comment]
rls-vscode set https://github.com/rust-lang-nursery/rls-vscode/blob/5729f5df951b7f932e7d1f6cd47dcdf0083186c1/src/extension.ts#L43 RUST_SRC_PATH if it's not set

I made this pr after #107 because this is more easy to have a one copy paste to set up a language server

I understand your point of view, i export my env variables in my shell rc too, but I think having all the conf to run the language server is more noob firendly

**Comment by autozimu** [comment]
In terms of user friendly, I believe the right approach would be replicating the same logic from rls-vscode. Adding extra layer can only create more confusion.

**Pull request closed without merging**
