### PR TITLE
Fix clippy::clone-on-copy

### PR DESCRIPTION
**Pull request by spk**
Hi! This fix one clippy warning. Cheers!

### CODE REVIEW

**Comment by dimbleby** [comment]
overlaps #868

**Comment by autozimu** [comment]
Thanks for contributing!

As #868 was submitted first, I merged in that changes.

Please rebase and update if you want to get the changes in.

**Comment by spk** [comment]
Did not saw the #868 this is rebased and include only the clippy fix

**Comment by autozimu** [comment]
Thanks!

**Pull request merged**
