### PR TITLE
fix compile warnning, auto open quickfix or location-list when selection ui is not fzf

### PR DESCRIPTION
**Pull request by ghost**
fix compile warnning, auto open quickfix or location-list when selection ui is not fzf

### CODE REVIEW

**Comment by dimbleby** [comment]
I've thought about this myself, but perhaps not everyone wants this behaviour.  So maybe a better approach would be to emit a custom event on completing a request (`doautocmd User ...`), which users could match on if they cared to do so?

See #620 for reasons not to fix the compiler warning.

**Comment by cairijun** [comment]
Perhaps an option for this? I didn't notice this pr until I made this: https://github.com/richardtsai/LanguageClient-neovim/commit/eee73c6a2414afe360a92448eb7ee86b78f25658

**Comment by autozimu** [comment]
The compile warning has been resolved.

Please add an option to allow customize this behavior.

**Review by autozimu — CHANGES_REQUESTED** [review]
Please check previous comment for adding an option for this behaviour change.

**Comment by Cosson2017** [comment]
Already added！

**Comment by ghost** [comment]
@autozimu 
Already added！

**Pull request closed without merging**
