### PR TITLE
[WIP] add rustDocument extension handlers

### LINKED ISSUE #50: Provide a way to query analysis progress for RLS
This would be possible by using `textDocument/diagnosticsBegin` and `textDocument/diagnosticsEnd`.

I'd like to be able to write an airline extension that displays the progress of the analysis, like the status bar of the RLS vscode plugin.

From a quick googling it appears that these methods are RLS-specific.

### PR DESCRIPTION
**Pull request by euclio**
Fixes #50.

Is this what you had in mind, @autozimu?

### CODE REVIEW

**Comment by autozimu** [comment]
(I thought I've already replied this thread, but it seems it didn't show up.)

Yes, that's pretty much it.

**Comment by euclio** [comment]
Do you intend to merge this?

**Comment by autozimu** [comment]
Not right now.

Could you remove the `g:LanguageClient_diagnosticsHandler`? As the functionality is not related to this project directly.

You could check existence of your handler directly.

**Comment by euclio** [comment]
I'm going to go ahead and close this. Displaying the unhandled handlers at the bottom is good enough for my use case, and there will probably be a better solution once neovim has language client support built-in.

**Pull request closed without merging**
