### PR TITLE
make the preivew window close automatically

### PR DESCRIPTION
**Pull request by framlog**
a.t.

### CODE REVIEW

**Comment by afnanenayet** [comment]
Why did you switch from using `env` for finding the home directory to the `dirs` crate?

**Comment by framlog** [comment]
@afnanenayet because that `std::env::home_dir` is deprecated.

**Comment by dimbleby** [comment]
Should at the very least separate the `home_dir` thing into its own commit I'd think.  Anyway, see #620 for discussion of why this may be unwanted.

See also #645 for discussion about closing the preview window.

**Comment by afnanenayet** [comment]
Ah I see, I think I agree that switching to the new crate should be a separate PR/issue,  given the concerns that were raised in #620

**Comment by framlog** [comment]
@dimbleby Thanks for your notice. I don't think this PR is needed after reading the author's view.

**Pull request closed without merging**
