### PR TITLE
Advertise code action support

### LINKED ISSUE #1037: Code actions broken on newest rust-analyzer
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. Yes
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes
- Did you check [troubleshooting]? Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

Starting from [2020-05-25](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-05-25), rust-analyzer returns no code actions to LanguageClient-neovim.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`): v0.4.3
- This plugin version (`git rev-parse --short HEAD`): 7c741d0
- This plugin's binary version (`bin/languageclient --version`): 0.1.156
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rust-analyzer'],
    \ }
let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```
- Language server link and version: https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-05-25/rust-analyzer-linux

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

- `cargo new temp`
- `nvim -u min-vimrc.vim temp/src/main.rs`
- `:call LanguageClient_textDocument_codeAction()`

## Current behavior

Code actions shown on [2020-05-18](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-05-18) but not on [2020-05-25](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-05-25) or nightly.

## Expected behavior

Code actions shown.

## Screenshots

image

## Additional context

Log files for calling code action on 2020-05-18 and 2020-05-25:
[LanguageClient-old.log](https://github.com/autozimu/LanguageClient-neovim/files/4689521/LanguageClient-old.log)
[LanguageClient-new.log](https://github.com/autozimu/LanguageClient-neovim/files/4689520/LanguageClient-new.log)

### PR DESCRIPTION
**Pull request by YaLTeR**
Fixes https://github.com/autozimu/LanguageClient-neovim/issues/1037

### CODE REVIEW

**Comment by YaLTeR** [comment]
Hm, even though some code actions do show this way, they show without the `rust-analyzer`:
image
and I'm not sure I'm seeing all of actions I'm supposed to see. Not sure why.

**Comment by martskins** [comment]
Haven't looked too much into this, but it seems to me like command based actions have been removed now in rust-analyzer (https://github.com/rust-analyzer/rust-analyzer/pull/4494/files#diff-cb373ef102a169ef5e1af6f370fd21ccL718) and they seem to now use a different struct for the CodeActions, it would be nice to get the payload of the response from rust-analyzer and maybe check that it correctly deserializes to a `lsp_types::CodeActionOrCommand`.

On another note, you might want to rebase this to `dev` and change the target branch to it as well, as per [this](https://github.com/autozimu/LanguageClient-neovim/blob/next/.github/CONTRIBUTING.md#submit-pr
). There are some changes around code actions in ranges there that might be worth testing too.

**Comment by YaLTeR** [comment]
I rebased my changes onto dev and I see two issues:
1. `LanguageClient_textDocument_codeAction()` is broken (only the `#` version works).
1. For some reason on my vimrc the code actions take several seconds to actually apply and, strangely enough, also several seconds to undo with a `u` for large files (like `src/language_server_protocol.rs`). This was not the case when based on the `next` branch and this is also not the case with `min-vimrc`. I've no idea what causes this, any help?

Visual code actions seem to work fine.

**Comment by martskins** [comment]
About the first issue, I think it's because `LanguageClient_textDocument_codeAction` calls this: 
 `call('LanguageClient#textDocument_codeAction', 'n', a:000)`, but it really should be calling this `call('LanguageClient#textDocument_codeAction', a:000)`. (Note there's one parameater less there). I can raise a PR to fix this but if you are comfortable including that in this PR I say go for it.

The second issue I could not reproduce, checked out your PR and tried with `LanguageClient-neovim` 's code base and both visual and single line code actions show and apply in a very short time.

PS: remember to also change the target branch of the PR

**Comment by YaLTeR** [comment]
> About the first issue, I think it's because `LanguageClient_textDocument_codeAction` calls this:
> `call('LanguageClient#textDocument_codeAction', 'n', a:000)`, but it really should be calling this `call('LanguageClient#textDocument_codeAction', a:000)`. (Note there's one parameater less there). I can raise a PR to fix this but if you are comfortable including that in this PR I say go for it.

Could you make a separate PR please?

> The second issue I could not reproduce, checked out your PR and tried with `LanguageClient-neovim` 's code base and both visual and single line code actions show and apply in a very short time.

Yeah, I'll check the profile log to see what causes it.

> PS: remember to also change the target branch of the PR

Oh, right, thanks.

**Comment by martskins** [comment]
Sure, opened #1039 to fix that.

**Comment by YaLTeR** [comment]
I found how to reproduce the hang issue: `set foldmethod=syntax`. All these seconds it seems to spend recomputing fold and syntax information.

But "good" news is that I was wrong and it is also present on the `next` branch, so it's not a new issue.

**Comment by YaLTeR** [comment]
I pushed a fix for the empty string action kind, I think the PR is good to merge now.

**Comment by autozimu** [comment]
Thanks!

**Pull request merged**
